#pragma once
#include "NodeBase.h"

#include "Functions/SineNode.h"
#include "Functions/CosineNode.h"
#include "Functions/CrossProductNode.h"
#include "Functions/DotProductNode.h"
#include "Functions/LengthNode.h"
#include "Functions/NormalizeNode.h"
#include "Functions/TangentNode.h"
#include "Functions/PowerNode.h"

#include "Inputs/UVNode.h"
#include "Inputs/WorldNormalNode.h"
#include "Inputs/WorldPositionNode.h"
#include "Inputs/FragmentCoordinateNode.h"

#include "Math/AddNode.h"
#include "Math/FloatNode.h"
#include "Math/SubtractNode.h"
#include "Math/MultiplyNode.h"
#include "Math/DivideNode.h"
#include "Math/DecimalNode.h"
#include "Math/Vector2Node.h"
#include "Math/Vector3Node.h"
#include "Math/Vector4Node.h"
#include "Math/SplitVectorNode.h"

#include "Rendering/TextureNode.h"
#include "Rendering/BSDFNode.h"